### PR TITLE
Various cleanups / documentation 

### PR DESCRIPTION
**Pull request by ened**
As a required task for the move to flutter community, the package needs to be in a good condition & score on pub.

### CODE REVIEW

**Comment by spiritinlife** [comment]
@ened is there a timeline/roadmap for the next release and the move to flutter community?

**Comment by ened** [comment]
@spiritinlife a couple of days I hope. Should be ready for a beta release on pub after #100 is merged.

**Comment by spiritinlife** [comment]
@ened Is there something that i could help with. I am using flutter_upload in production for an app ( [Vendora.gr](https://play.google.com/store/apps/details?id=gr.vendora.app) ) with 100k downloads. 

Could perform some prod tests if you want to ensure stability. 
Send me an email on george.chailazopoulos@gmail.com if you want to discuss further.

**Comment by ened** [comment]
@spiritinlife OK will email

**Pull request merged**
