### PR TITLE
Refactor multiform upload to better implementation and handle uploading large file. this will fix #24, #25, #27

### LINKED ISSUE #24: Copy selected file not working on iOS 13.1.2
When I tried to make a copy of the selected file using the file copy method

`var file = selectedVideo.Copy('$saveDir/$filename');`

I am getting a below error

`Cannot copy file` 
`OSError 
errorCode:2
message: No such file or directory`

The same code works fine on the version below 13.

### PR DESCRIPTION
**Pull request by onikiri2007**
* Current multipart form upload implementation has the potential to run out of memory when uploading large files since it loads the whole file into memory and writes to the request file.
this PR will attempt to fix that. code has been copied from Alamofire. their multiplatform data has a better implementation.

* Refactor example app to send the direct video/image path instead of copying and let the platform take care of the rest.

This should fix with issue #24, #25, #27

### CODE REVIEW

**Comment by ened** [comment]
@onikiri2007 - Before going into much detail: Have you considered depending on Alamofire instead of copying the code in? We can always strip out unused components on a release build, therefore I don't think package size is a major concern at the moment.

Also, good to not copy a requested file twice (in the example), and let the form builder be standardised. Will the Alamofire uploader make a copy of the request and store it in cache, though?

**Comment by onikiri2007** [comment]
> @onikiri2007 - Before going into much detail: Have you considered depending on Alamofire instead of copying the code in? We can always strip out unused components on a release build, therefore I don't think package size is a major concern at the moment.
> yeah that's a good idea. I'll change to make Alamorefire as dependency

> Also, good to not copy a requested file twice (in the example), and let the form builder be standardised. Will the Alamofire uploader make a copy of the request and store it in cache, though? I'm not sure what you mean by this? Do you mean creating the request body as file? if this is the case, the answer is yes because urlsession only accept file as request body therefore It requires to create the one single file with all the files append. Alamofire's FormData class take care the better in this scenario.

**Comment by ened** [comment]
> > Also, good to not copy a requested file twice (in the example), and let the form builder be standardised. Will the Alamofire uploader make a copy of the request and store it in cache, though? 

> I'm not sure what you mean by this? Do you mean creating the request body as file? if this is the case, the answer is yes because urlsession only accept file as request body therefore It requires to create the one single file with all the files append. Alamofire's FormData class take care the better in this scenario.

OK, so it's only a code cleanup for the form data builder, sounds good!

**Comment by onikiri2007** [comment]
first one is done. Alamofire is now dependency. I might refactor the Urlsession part also later to use Alamofire's sessionManager instead. for now this will be first refactoring.

**Comment by ened** [comment]
@onikiri2007 , ok - just two things left from my point of view:
 - please update the Podfile.lock (by running pod update)
 - please try to run SwiftLint or similar to remove the whitespace changes (a lot of lines' only change is addition of white spaces)

We'll do SwiftLint on CI in the future as well.

**Comment by onikiri2007** [comment]
> @onikiri2007 , ok - just two things left from my point of view:
> 
> * please update the Podfile.lock (by running pod update)
> * please try to run SwiftLint or similar to remove the whitespace changes (a lot of lines' only change is addition of white spaces)
> 
> We'll do SwiftLint on CI in the future as well.

clean up is done
@ened  Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies. requires to update the podspec repo in CI

**Comment by ened** [comment]
@onikiri2007 please rebase

**Pull request merged**
